Menbook.Web/Areas/Blog/Controllers/ArticlesController.cs
namespace Menbook.Web.Areas.Blog.Controllers
{
    using Data.Models;
    using Helpers.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services;
    using System;
    using System.Threading.Tasks;

    public class ArticlesController : BlogBaseController
    {
        private const int PageSize = 3;

        private readonly UserManager<User> userManager;
        private readonly IUserService users;
        private readonly IBlogArticleService articles;
        private readonly IHtmlService html;

        public ArticlesController(UserManager<User> userManager, IUserService users, IBlogArticleService articles, IHtmlService html)
        {
            this.userManager = userManager;
            this.users = users;
            this.articles = articles;
            this.html = html;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int page = 1)
            =>View(new ArticleListingViewModel
            {
                Articles = await this.articles.AllAsync(page, PageSize),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling((double)await this.articles.TotalAsync() / PageSize),
                CurrentUserName = await this.users.CurrentUserNameByIdAsync(this.userManager.GetUserId(User))
            });
        
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var article = await this.articles.ByIdAsync(id);

            return View(article);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(PublishArticleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.Content = this.html.Sanitize(model.Content);

            var userId = this.userManager.GetUserId(User);

            await this.articles.CreateAsync(model.Title, model.Content, userId);

            TempData.AddSuccessMessage($"Article {model.Title} was created by {this.userManager.GetUserName(User)}");

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeleteArticle(int ArticleId, int page)
        {
            bool success = await this.articles.DeleteByIdAsync(ArticleId);

            if (!success)
            {
                return BadRequest();
            }
            
            return RedirectToAction(nameof(Index), new { page });
        }
    }
}

Menbook.Web/Areas/Blog/Views/Articles/Create.cshtml
@model PublishArticleViewModel
@{
    ViewData["Title"] = "Publish Article";
}
<h2>@ViewData["Title"]</h2>

<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
<script>tinymce.init({ selector: 'textarea' });</script>
<hr />

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content"></label>
                <textarea asp-for="Content" rows="30" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-success">Publish Article</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Menbook.Web/Areas/Blog/Views/Articles/Details.cshtml
@model ArticleDetailsServiceModel
@{
    ViewData["Title"] = $"{Model.Title}";
}

@{
    var authorImage = Model.AuthorImage == null ? "http://philosophy.ucr.edu/wp-content/uploads/2014/10/no-profile-img-240x300.gif" : Model.AuthorImage;
}
<br />
<div class="card" style="background-color:lightblue;">
    <div class="col-md-12">
        <div class="col-md-8 col-md-offset-2">
            <br /><br />
            <div class="text-center">
                <img class="card-img-top img-circle text-center" src="@authorImage" alt="@Model.Author" height="200" width="200">
            </div>
            <br />
            <div class="card-block">
                <h2 class="card-title text-center"><strong>@Model.Title</strong></h2><br /><br />
                <p class="card-text">@Html.Raw(@Model.Content)</p>
                <br />
                <div class="text-right"><em>Author: @Model.Author<br />published on @Model.PublishDate.ToShortDateString()</em></div>
            </div>
        </div>
    </div>
</div>

Menbook.Web/Areas/Blog/Views/Articles/Index.cshtml
@model ArticleListingViewModel
@{
    ViewData["Title"] = "All Articles";
}

<br /><br /><a asp-action="Create" class="btn btn-primary">Create new Article</a>
<nav aria-label="Page navigation example" class="text-center">
    <ul class="pagination">
        <li class="page-item"><a asp-route-page="@Model.PreviousPage" class="page-link">Previous</a></li>

        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            var activePage = Model.CurrentPage == i ? "active" : string.Empty;
            <li class="page-item @activePage"><a asp-route-page="@i" class="page-link"> @i </a></li>
        }
        <li class="page-item"><a asp-route-page="@Model.NextPage" class="page-link">Next</a></li>
    </ul>
</nav>

@foreach (var article in Model.Articles)
{
    var authorImage = article.AuthorImage == null ? "http://philosophy.ucr.edu/wp-content/uploads/2014/10/no-profile-img-240x300.gif" : article.AuthorImage;

    <div class="card" style="background-color:lightblue; height: 300px;">
        <div class="col-md-10 col-md-offset-1">
        <div class="col-md-5 text-center">
            <br /><br />
            <img class="card-img-top img-circle" src="@authorImage" alt="@article.Author" height="200" width="200">
        </div>
        <div class="col-md-6">
            <br />
            <div class="text-right">
                @if (Model.CurrentUserName == article.Author)
                {
                    <form method="post" asp-controller="Articles" asp-action="DeleteArticle">
                        <input type="hidden" name="ArticleId" value="@article.Id" />
                        <input type="hidden" name="page" value="@Model.CurrentPage" />
                        <button class="btn btn-danger">Delete</button>
                    </form>
                }
                <div class="card-block">
                    <br />
                    <h1 class="card-title text-center"><strong>@article.Title</strong></h1><br />
                    <div class="text-right">
                        <br />
                        <em>
                            Author: @article.Author
                            <br />published on @article.PublishDate.ToShortDateString()
                        </em>
                    </div><br />
                    <p class="card-text"><a asp-action="Details" asp-route-id="@article.Id" class="btn btn-success  form-control">Read More ...</a></p>
                </div>
            </div>
        </div>
    </div></div>
    <br /><br />
}

<nav aria-label="Page navigation example" class="text-center">
    <ul class="pagination">
        <li class="page-item"><a asp-route-page="@Model.PreviousPage" class="page-link">Previous</a></li>

        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            var activePage = Model.CurrentPage == i ? "active" : string.Empty;
            <li class="page-item @activePage"><a asp-route-page="@i" class="page-link"> @i </a></li>
        }
        <li class="page-item"><a asp-route-page="@Model.NextPage" class="page-link">Next</a></li>
    </ul>
</nav>