Menbook.Web/Areas/Beers/Controllers/CalculatorController.cs
namespace Menbook.Web.Areas.Beers.Controllers
{
    using Menbook.Data.Models;
    using Menbook.Web.Areas.Beers.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Services;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class CalculatorController : BaseBeerController
    {
        private readonly IBeerService beers;
        private readonly IUserService users;
        private readonly UserManager<User> userManager;

        public CalculatorController(IBeerService beers, IUserService users, UserManager<User> userManager)
        {
            this.beers = beers;
            this.users = users;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var form = new CalculateFormViewModel
            {
                BeerNames = this.GetSupplierListItems(),
                Age = await this.users.CurrentUserAgeByIdAsync(this.userManager.GetUserId(User))
            };

            return View(form);
        }

        [Authorize]
        public async Task<IActionResult> Result(CalculateFormViewModel model)
        {
            var age = model.Age;
            var weight = model.Weight;
            var drinkingHours = model.HoursDrinking;
            var totalDrinks = model.TotalDrinks;
            var beerAbv = await this.beers.GetAbvBIdAsync(model.BeerId);

            var bacResult = BAC.Calculate(age, weight, drinkingHours, totalDrinks, beerAbv);

            var bacConclusion = BAC.Conclusion(bacResult/10.0);
            bacConclusion.Bac = bacResult;
            bacConclusion.ImageUrl = "https://fthmb.tqn.com/mm0XORjQpYtckiap7AQsuklUkJM=/768x0/filters:no_upscale()/homer_2008_v2F_hires2-56a00fd43df78cafda9fde98.jpg";

            return View(nameof(Result), bacConclusion);
        }

        private IEnumerable<SelectListItem> GetSupplierListItems()
            => this.beers
                    .GetAllNamesAsync()
                    .Select(s => new SelectListItem
                    {
                        Text = s.Name,
                        Value = s.Id.ToString()
                    })
                    .ToList();
    }
}

Menbook.Web/Areas/Beers/Views/Calculator/Index.cshtml
@model CalculateFormViewModel
@{
    ViewData["Title"] = "Index";
}

<br />

<div class="row">
    <div class="col-md-6 col-md-offset-2" style="background-image:url('https://fthmb.tqn.com/mm0XORjQpYtckiap7AQsuklUkJM=/768x0/filters:no_upscale()/homer_2008_v2F_hires2-56a00fd43df78cafda9fde98.jpg');background-size:cover; height:500px;width:750px;">
        <section>
            <form asp-controller="Calculator" asp-action="Result">
                <div class="row">
                    <br />
                    <div class="col-md-12" style="height:430px">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Age"></label>
                                <input asp-for="Age" placeholder="Name" class="form-control" />
                                <span asp-validation-for="Age" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Weight"></label>
                                <input asp-for="Weight " placeholder="Country" class="form-control" />
                                <span asp-validation-for="Weight" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BeerId"></label>
                                <select asp-for="BeerId" asp-items="@Model.BeerNames" class="form-control"></select>
                                <span asp-validation-for="BeerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="TotalDrinks"></label>
                                <input asp-for="TotalDrinks" placeholder="Name" min="1" max="20" class="form-control" />
                                <span asp-validation-for="TotalDrinks" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="HoursDrinking"></label>
                                <input asp-for="HoursDrinking" type="number" step="0.5" min="0.5" max="10" placeholder="Country" class="form-control" />
                                <span asp-validation-for="HoursDrinking" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="form-group text-right">
                    <button type="submit" class="btn btn-primary">Calculate</button>
                </div>
            </form>
        </section>
    </div>
</div>
<br />

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Menbook.Web/Areas/Beers/Views/Calculator/Result.cshtml
@model CalculatorResultViewModel
@{
    ViewData["Title"] = "Result";
}
<br />
<div class="row">
    <div class="col-md-6 col-md-offset-2" style="height:500px;width:750px;background-image:url('@Model.ImageUrl');background-size:cover;">
        <div class="col-md-12" style="height:450px">
            <h2>Blood Alcohol Content : @($"{Model.Bac:F2}")</h2>
            <br />
            <div class="col-md-6">
                <h4 style="color:red"><strong>@Model.Conclusion</strong></h4>
            </div>
        </div>
        <br />
        <div class="text-right">
            <a asp-action="Index" class="btn btn-primary">
                Calculate Again
            </a>
        </div>
    </div>
</div>
<br />