Menbook.Web/Areas/Beers/Models/AddBeerFormModel.cs
namespace Menbook.Web.Areas.Beers.Models
{
    using Data.Models.Beers;
    using System.ComponentModel.DataAnnotations;

    using static Data.DataConstrants;

    public class AddBeerFormModel
    {
        [Required]
        [MinLength(BeerNameMinLength)]
        [MaxLength(BeerNameMaxLength)]
        public string Name { get; set; }

        [Required]
        [MinLength(BeerCountryMinLength)]
        [MaxLength(BeerCountryMaxLength)]
        public string Country { get; set; }

        public BeerType Type { get; set; }

        [Range(0, 100)]
        [Display(Name = "Alcohol By Volume (ABV)")]
        public double AlcoholByVolume { get; set; }

        [Display(Name = "Image Url")]
        public string ImageUrl { get; set; }
    }
}

Menbook.Web/Areas/Beers/Models/BAC.cs
namespace Menbook.Web.Areas.Beers.Models
{
    public static class BAC
    {
        public static double Calculate(int age, int weight, double drinkingHours, int totalDrinks, double beerAbv)
        {
            var alcoholMass = totalDrinks * 0.5 * (beerAbv / 100.0 * 789.24);

            var bac = ((0.806 * alcoholMass * 1.2) / (0.58 * weight)) - (0.015 * drinkingHours);

            return bac;
        }

        public static CalculatorResultViewModel Conclusion(double bacResult)
        {
            var conclusion = string.Empty;
            var imageUrl = string.Empty;
            
            if (bacResult <= 0.01)
            {
                conclusion = "You're really not feeling the effects of alcohol right now.";
                imageUrl = "https://fthmb.tqn.com/mm0XORjQpYtckiap7AQsuklUkJM=/768x0/filters:no_upscale()/homer_2008_v2F_hires2-56a00fd43df78cafda9fde98.jpg";
            }
            else if (bacResult > 0.01 && bacResult <= 0.03)
            {
                conclusion = "You might feel a little more relaxed, perhaps a little light-headed. If you're shy you might lose a bit of your shyness. The typical depressant effects of alcohol are not affecting you at this stage and you probably haven’t lost any of your coordination.";
                imageUrl = "http://www.quotesforbros.com/wp-content/uploads/2015/10/Homer_Simpson_Vector_by_bark2008.png";
            }
            else if (bacResult > 0.03 && bacResult <= 0.06)
            {
                conclusion = "You're probably feeling a bit relaxed or you might have a feeling of well - being or euphoria (feeling really good or really positive). You might feel a bit warmer than you usually do. Your behavior might be a bit exaggerated or your emotions might be a bit intensified. You're probably feeling some impairment of reasoning and memory and since your level of caution is lower, it's a bad idea to drive.";
                imageUrl = "http://media.silabg.com/uf/common/homer_beer_muscle-1.jpg";
            }
            else if (bacResult > 0.06 && bacResult <= 0.09)
            {
                conclusion = "Although you can definitely tell you've been drinking, and you're probably aware that you're feeling some effects of alcohol, you might believe that you're more alert than you really are. In reality, with a BAC of 0.07 – 0.09 you'll be experiencing a slight impairment of speech, balance and hearing and your reaction time is reduced. Your caution, reasoning and memory are impaired, and your judgment and level of self-control are reduced.";
                imageUrl = "http://2.bp.blogspot.com/-0ohNNqTlk34/TcX29A7KqwI/AAAAAAAADOU/NPN68ZdFNhI/s1600/homerkeg.gif";
            }
            else if (bacResult > 0.09 && bacResult <= 0.12)
            {
                conclusion = "If your BAC is between 0.10 and 0.125 your speech will be slurred and your balance, vision, reactions time and hearing will be impaired. Your motor coordination will also be significantly impaired and you'll have a loss of good judgment.";
                imageUrl = "http://blog.campstay.com.au/wp-content/uploads/DuffBeerHomerSimpson.jpg";
            }
            else if (bacResult > 0.12 && bacResult <= 0.15)
            {
                conclusion = "Right now, you'd be feeling gross motor impairment and a lack of physical control. It'd probably be hard for you to type on the keyboard and your monitor or mobile phone screen would appear blurry. Your judgment and perception of what’s going on would be severely impaired and any feeling of euphoria (feeling really good or really positive) you had earlier will have turned to dysphoria (an emotional state of agitation, unease or depression). You'd have gross motor impairment and a lack of physical control.";
                imageUrl = "https://c1.staticflickr.com/5/4173/34455533212_b6444e506c_z.jpg";
            }
            else if (bacResult > 0.15 && bacResult <= 0.19)
            {
                conclusion = "You'll probably start to feel sick to your stomach. Any euphoria (feeling really good or really positive) you had earlier will have turned to dysphoria (an emotional state of agitation, unease or depression). Right now you might look like a sloppy drunk.";
                imageUrl = "https://www.kegworks.com/wp/wp-content/uploads/2013/05/HomerSimpson22.gif";
            }
            else if (bacResult > 0.19 && bacResult <= 0.21)
            {
                conclusion = "If your BAC is 0.20, you'll probably need help if you want to walk properly. If you fall down you probably won't feel a lot of pain – even if you hurt yourself. At this level of BAC, some people begin to vomit. At the very least, you'll feel dazed, confused and disoriented.";
                imageUrl = "http://img.timesnownews.com/zoom/story/1513186830-homer_beer.jpg?d=400x300";
            }
            else if (bacResult > 0.21 && bacResult <= 0.30)
            {
                conclusion = "If you were awake at this point you'd have very little comprehension as to where you were or what you were doing. You might pass out suddenly and it'd be hard to wake you up.";
                imageUrl = "http://www.freeduh.com/wp-content/uploads/2010/12/homer-simpson-with-111th-congress-tshirt-and-drunk-on-spending-beer.png";
            }
            else
            {
                conclusion = "It's possible that you might fall into a coma. You might die due to the paralysis of your diaphragm, the collapse of your lungs, or heart attack (any form of respiratory arrest).";
                imageUrl = "https://i.ebayimg.com/images/g/XtoAAOSwjk9ZTrlO/s-l300.jpg";
            }

            return new CalculatorResultViewModel
            {
                Conclusion = conclusion,
                ImageUrl = imageUrl
            };
        }
    }
}

Menbook.Web/Areas/Beers/Models/BeerListingViewModel.cs
namespace Menbook.Web.Areas.Beers.Models
{
    using Services.Models.Beers;
    using System.Collections.Generic;

    public class BeerListingViewModel
    {
        public IEnumerable<BeerListingServiceModel> Beers { get; set; }

        public int TotalPages { get; set; }

        public int CurrentPage { get; set; }

        public int PreviousPage => this.CurrentPage <= 1 ? 1 : this.CurrentPage - 1;

        public int NextPage => this.CurrentPage >= this.TotalPages ? this.TotalPages : this.CurrentPage + 1;

        public string CurrentUserId { get; set; }

        public IDictionary<int, int> CurrentUserRatedBeerIds { get; set; }
    }
}

Menbook.Web/Areas/Beers/Models/CalculateFormViewModel.cs
namespace Menbook.Web.Areas.Beers.Models
{
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class CalculateFormViewModel
    {
        [Required]
        [Range(15,100)]
        public int Age { get; set; }

        [Required]
        [Range(50, 150)]
        public int Weight { get; set; }

        [Range(0.5, 12)]
        [Display(Name = "Drinking Hours")]
        public double HoursDrinking { get; set; }

        [Range(1,20)]
        [Display(Name = "Total Drinks")]
        public int TotalDrinks { get; set; }

        [Display(Name = "Beer")]
        public int BeerId { get; set; }

        public IEnumerable<SelectListItem> BeerNames { get; set; }
    }
}

Menbook.Web/Areas/Beers/Models/CalculatorResultViewModel.cs
namespace Menbook.Web.Areas.Beers.Models
{
    public class CalculatorResultViewModel
    {
        public string Conclusion { get; set; }

        public string ImageUrl { get; set; }

        public double Bac { get; set; }
    }
}

Menbook.Web/Areas/Beers/Models/EditBeerFormViewModel.cs
namespace Menbook.Web.Areas.Beers.Models
{
    using Data.Models.Beers;
    using System.ComponentModel.DataAnnotations;

    using static Data.DataConstrants;

    public class EditBeerFormViewModel
    {
        public int Id { get; set; }

        [Required]
        [MinLength(BeerNameMinLength)]
        [MaxLength(BeerNameMaxLength)]
        public string Name { get; set; }

        [Required]
        [MinLength(BeerCountryMinLength)]
        [MaxLength(BeerCountryMaxLength)]
        public string Country { get; set; }

        public BeerType Type { get; set; }

        [Range(0, 100)]
        [Display(Name = "Alcohol By Volume (ABV)")]
        public double AlcoholByVolume { get; set; }

        [Display(Name = "Image Url")]
        public string ImageUrl { get; set; }

        public int CurrentPage { get; set; }
    }
}

Menbook.Web/Areas/Beers/Models/SearchBeerListingViewModel.cs
namespace Menbook.Web.Areas.Beers.Models
{
    public class SearchBeerListingViewModel : BeerListingViewModel
    {
        public string Search { get; set; }

        public int TotalFound { get; set; }
    }
}

Menbook.Web/Areas/Blog/Models/ArticleListingViewModel.cs
namespace Menbook.Web.Areas.Blog.Models
{
    using Services.Models.Blog;
    using System.Collections.Generic;

    public class ArticleListingViewModel
    {
        public IEnumerable<ArticleListingServiceModel> Articles { get; set; }

        public int TotalPages { get; set; }

        public int CurrentPage { get; set; }

        public int NextPage => this.CurrentPage >= this.TotalPages ? this.TotalPages : this.CurrentPage + 1;

        public int PreviousPage => this.CurrentPage <= 1 ? 1 : this.CurrentPage - 1;

        public string CurrentUserName { get; set; }
    }
}

Menbook.Web/Areas/Blog/Models/PublishArticleViewModel.cs
namespace Menbook.Web.Areas.Blog.Models
{
    using Data;
    using System.ComponentModel.DataAnnotations;

    public class PublishArticleViewModel
    {
        [Required]
        [MinLength(DataConstrants.ArticleTitleMinLength)]
        [MaxLength(DataConstrants.ArticleTitleMaxLength)]
        public string Title { get; set; }

        public string Content { get; set; }
    }
}

Menbook.Web/Areas/Cars/Models/AddCarToFavouriteForm.cs
namespace Menbook.Web.Areas.Cars.Models
{
    public class AddCarToFavouriteForm
    {
        public string Model { get; set; }
    }
}

Menbook.Web/Areas/Cars/Models/AddImgToModelForm.cs
namespace Menbook.Web.Areas.Cars.Models
{
    public class AddImgToModelForm
    {
        public int MakeId { get; set; }

        public string Make { get; set; }

        public string Model { get; set; }

        public string ImageUrl { get; set; }
    }
}

Menbook.Web/Areas/Cars/Models/CarDetailsViewModel.cs
namespace Menbook.Web.Areas.Cars.Models
{
    using Services.Models;
    using System.Collections.Generic;

    public class CarDetailsViewModel
    {
        public CarDetailsServiceModel Car { get; set; }

        public IEnumerable<string> UserReviewIds { get; set; }

        public string CurrentUserId { get; set; }
    }
}

Menbook.Web/Areas/Cars/Models/CarMakeListingViewModel.cs
namespace Menbook.Web.Areas.Cars.Models
{
    using System.Collections.Generic;
    using Services.Models;

    public class CarMakeListingViewModel
    {
        public IEnumerable<CarMakeListingServiceModel> Cars { get; set; }

        public int TotalPages { get; set; }

        public int CurrentPage { get; set; }

        public int PreviousPage => this.CurrentPage == 1 ? this.CurrentPage : this.CurrentPage - 1;

        public int NextPage => this.CurrentPage >= this.TotalPages ? this.CurrentPage : this.CurrentPage + 1;
    }
}

Menbook.Web/Areas/Cars/Models/CarModelListingViewModel.cs
namespace Menbook.Web.Areas.Cars.Models
{
    using Services.Models;
    using System.Collections.Generic;

    public class CarModelListingViewModel
    {
        public IEnumerable<CarModelListingServiceModel> Models { get; set; }

        public string MakeName { get; set; }

        public IEnumerable<int> UserCarFavouriteIds { get; set; }

        public IDictionary<int, int> UserRateIds { get; set; }

        public IDictionary<int, double> AverageRating { get; set; }
    }
}

Menbook.Web/Areas/Cars/Models/CreateModelFormViewModel.cs
namespace Menbook.Web.Areas.Cars.Models
{
    using Data;
    using System.ComponentModel.DataAnnotations;

    public class CreateModelFormViewModel
    {
        public int MakeId { get; set; }

        [Required]
        [MinLength(DataConstrants.CarMakeNameMinLength)]
        [MaxLength(DataConstrants.CarMakeNameMaxLength)]
        public string Name { get; set; }

        [MinLength(DataConstrants.UrlMinLength)]
        [MaxLength(DataConstrants.UrlMaxLength)]
        public string ImageUrl { get; set; }
    }
}

Menbook.Web/Areas/Cars/Models/SearchCarMakeListingViewModel.cs
namespace Menbook.Web.Areas.Cars.Models
{
    public class SearchCarMakeListingViewModel : CarMakeListingViewModel
    {
        public string Search { get; set; }

        public int TotalFound { get; set; }
    }
}

Menbook.Web/Models/AccountViewModels/ExternalLoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Menbook.Web.Models.AccountViewModels
{
    public class ExternalLoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}

Menbook.Web/Models/AccountViewModels/ForgotPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Menbook.Web.Models.AccountViewModels
{
    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}

Menbook.Web/Models/AccountViewModels/LoginViewModel.cs
namespace Menbook.Web.Models.AccountViewModels
{
    using System.ComponentModel.DataAnnotations;

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Username")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

Menbook.Web/Models/AccountViewModels/LoginWith2faViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Menbook.Web.Models.AccountViewModels
{
    public class LoginWith2faViewModel
    {
        [Required]
        [StringLength(7, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Text)]
        [Display(Name = "Authenticator code")]
        public string TwoFactorCode { get; set; }

        [Display(Name = "Remember this machine")]
        public bool RememberMachine { get; set; }

        public bool RememberMe { get; set; }
    }
}

Menbook.Web/Areas/Cars/Controllers/MakesController.cs
namespace Menbook.Web.Areas.Cars.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services;
    using System;
    using System.Threading.Tasks;

    public class MakesController : CarsBaseController
    {
        private const int PageSize = 6;

        private readonly ICarService cars;

        public MakesController(ICarService cars)
        {
            this.cars = cars;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            string search = string.Empty;
            var cars = await this.cars.AllBySearchAsync(page, PageSize, search);
            var totalPages = (int)Math.Ceiling((double)await this.cars.Total() / PageSize);

            return View(new CarMakeListingViewModel
            {
                Cars = cars,
                CurrentPage = page,
                TotalPages = totalPages
            });
        }

        public async Task<IActionResult> Search(string Search, int page = 1)
        {
            if(Search == null)
            {
                return RedirectToAction(nameof(Index));
            }
            var cars = await this.cars.AllBySearchAsync(page, PageSize, Search);
            var totalPages = (int)Math.Ceiling((double) await this.cars.TotalBySearchAsync(Search) / PageSize);

            return View(new SearchCarMakeListingViewModel
            {
                Cars = cars,
                CurrentPage = page,
                TotalPages = totalPages,
                Search = Search,
                TotalFound = await this.cars.TotalBySearchAsync(Search)
            });
        }
    }
}

Menbook.Web/Areas/Cars/Views/Models/Create.cshtml
@model CreateModelFormViewModel
@{
    ViewData["Title"] = "Create";
}

<h2>Create Model</h2>

<div class="row" >
    <div class="col-md-8 col-md-offset-2" style="height:460px; background-image:url('http://i.ebayimg.com/images/i/292446975532-0-1/s-l1000.jpg');background-size:cover;">
        <section>
            <br /><br />
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" placeholder="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrl"></label>
                    <input asp-for="ImageUrl" placeholder="Image Url" class="form-control" />
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <input type="hidden" name="MakeId" value="@Model.MakeId" />
                <br /><br />
                <div class="form-group text-right">
                    <button type="submit" class="btn btn-primary">Save Model</button>
                </div><br />
            </form>
        </section>
    </div>
</div>
<br />

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Menbook.Web/Areas/Cars/Views/Models/Details.cshtml
@model CarDetailsViewModel
@{
    ViewData["Title"] = "Details";
}

<br /><br />
@{ 
    var carImageUrl = Model.Car.ImageUrl == null ? "http://forevervacationrentals.com/images/no-image-available2.jpg" : Model.Car.ImageUrl;
}
<div class="row">
    <div class="col-md-12">
        <div class="well well-sm" style="background-color:lightgray">
            <div class="row">
                <div class="col-sm-6 col-md-5" style="margin:20px">
                    <img src="@carImageUrl" alt="@Model.Car.Make @Model.Car.Model" class="img-circle img-responsive" />
                </div>
                <br /><br /><br />
                <div class="col-sm-6 col-md-5 col-md-offset-1">
                    <h1 class="text-center">
                        @Model.Car.Make @Model.Car.Model
                    </h1>
                    <br /><br />
                    <p>
                        <div class="col-md-12 text-center">
                            <strong>Make</strong>: @Model.Car.Make<br /><br />
                            <strong>Model</strong>: @Model.Car.Model<br /><br />
                        </div>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<br /><br />
@if (Model.UserReviewIds.Contains(Model.CurrentUserId))
{
    <h4 class="text-center text-warning">You have already posted review for this car. You can't post anymore...</h4>
}
else
{
    <h3 class="text-center text-danger">Post Review</h3>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form method="post" asp-action="PostReview">
                <textarea rows="5" name="Text" placeholder="Post your review here ..." class="form-control"></textarea>
                <input type="hidden" name="ModelId" value="@Model.Car.ModelId" />
                <div class="text-right">
                    <input type="submit" class="btn btn-primary text-right" value="Post Review" />
                </div>
            </form>
        </div>
    </div>
}

<br /><br />
@foreach (var review in Model.Car.Reviews)
{
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="list-group">
                <a class="list-group-item active text-left">
                    <h3 class="list-group-item-text">"@review.Text"</h3>
                    <br /><br />
                    <div class="text-right">
                        <em class="list-group-item-heading">published by @review.User on @review.PublishedDate.ToShortDateString()</em>
                    </div>
                </a>
            </div>
        </div>
    </div>

    <br /><br /><br /><br />
}

Menbook.Web/Areas/Cars/Views/Models/Index.cshtml
@model CarModelListingViewModel
@{
    ViewData["Title"] = $"{Model.MakeName}";
}    
<br />
<div class="">
    <a asp-action="Create" class="btn btn-primary">Add Model</a>
    <a asp-controller="Makes" asp-action="Index" class="btn btn-warning">Back to Makes</a>
</div>
<br />
@foreach (var car in Model.Models)
{
    var carImageUrl = car.ImageUrl == null ? "http://forevervacationrentals.com/images/no-image-available2.jpg" : car.ImageUrl;
    var averageRate = $"Average Rating - {Model.AverageRating[car.Id]:F1}";
    <div class="col-md-6" id="@car.Id">
        <div class="panel panel-default panel-front" style="height:600px;">
            <h2 class="text-center text-success">@Model.MakeName <em>@car.Name</em></h2>
            <h5 class="text-center text-info">@(Model.AverageRating[car.Id] > 0 ? @averageRate : "Be the first to rate this car") <img src="http://img.first-jump.com/icons/file/oxygen/128/actions/bookmark.png" width="20" /></h5>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="row text-center">
                    <div class="row">
                        @if (Model.UserRateIds.Keys.Contains(car.Id))
                        {
                            <div class="col-md-8 col-md-offset-2">
                                <div class="btn btn-success">You have already rated this car with @Model.UserRateIds[car.Id] <img src="http://img.first-jump.com/icons/file/oxygen/128/actions/bookmark.png" width="30" />!</div>
                            </div>
                        }
                        else
                        {
                            <div class="col-md-9 col-md-offset-2">
                                @for (int i = 1; i <= 5; i++)
                                {
                                    <form asp-action="RateCar" method="post" class="col-md-2">
                                        <input type="hidden" name="ModelId" value="@car.Id" />
                                        <input type="hidden" name="Rating" value="@i" />
                                        <input type="hidden" name="Make" value="@Model.MakeName" />
                                        <button type="submit" class="btn btn-danger">@i<img src="http://img.first-jump.com/icons/file/oxygen/128/actions/bookmark.png" width="30" /></button>
                                    </form>
                                }
                            </div><br />
                        }
                    </div><br />
                </div>
            }

            <div class="panel-heading" style="height:260px">
                <a asp-action="Details" asp-route-id="@car.Id" asp-route-title="@car.Name.ToFriendlyUrl()"><img style='width: 100%;' src="@carImageUrl" height="250" alt="@Model.MakeName @car.Name"></a>
            </div>

            @if (User.Identity.IsAuthenticated)
            {
                <div class="panel-body">
                    <div class="text-right">
                        @if (Model.UserCarFavouriteIds.Contains(car.Id))
                        {
                            <div class="text-center">
                                <div class="btn btn-default text-center">You already own this car <img src="http://icons.iconarchive.com/icons/designbolts/free-valentine-heart/256/Heart-Shadow-icon.png" width="20" /></div>
                            </div><br />
                        }
                        else
                        {
                            <form asp-action="AddToMyCar" method="post">
                                <input type="hidden" name="Id" value="@car.Id" />
                                <input type="hidden" name="Make" value="@Model.MakeName" />
                                <button type="submit" class="btn btn-info col-md-4 col-md-offset-4">Add to my cars <img src="http://icons.iconarchive.com/icons/designbolts/free-valentine-heart/256/Heart-Shadow-icon.png" width="20" /></button>
                            </form><br /><br /><br />
                        }

                        @if (car.ImageUrl == null)
                        {
                            <form asp-action="AddImg" method="post">
                                <div class="col-md-8">
                                    <input asp-for="@car.ImageUrl" name="ImageUrl" class="form-control" placeholder="Upload Picture Url for @Model.MakeName @car.Name" />
                                    <input type="hidden" name="Make" value="@Model.MakeName" />
                                    <input type="hidden" name="Model" value="@car.Name" />
                                </div>
                                <div class="col-md-4">
                                    <input type="submit" class="btn btn-warning form-control" value="Save Image" />
                                </div>
                            </form>
                        }
                        else
                        {
                            <form method="post" asp-action="DeleteImg">
                                <div class="col-md-8">
                                    <input type="hidden" name="Make" value="@Model.MakeName" />
                                    <input type="hidden" name="Model" value="@car.Name" />
                                    <input type="hidden" name="ImageUrl" value="@car.ImageUrl" />
                                </div>
                                <div class="col-md-4">
                                    <input type="submit" class="btn btn-danger form-control" value="Change Picture" />
                                </div>
                            </form>
                        }
                        <br /><br /><br />
                        <a asp-action="Details" asp-route-id="@car.Id" class="btn btn-success form-control">Details</a>
                    </div>
                </div>
            }
            else
            {
                <br /><br /><br /><br />
                <div class="panel-body">
                    <div class="text-right">
                        <a asp-area="" asp-controller="Account" asp-action="Login" asp-route-returnurl="@Html.ViewContext.HttpContext.Request.Path" class="btn btn-primary form-control">Login for more</a>
                        <br /><br />
                        <a asp-area="" asp-controller="Account" asp-action="Register" asp-route-returnurl="@Html.ViewContext.HttpContext.Request.Path" class="btn btn-success form-control">Register for more</a>
                    </div>
                </div>
            }
        </div>
    </div>
}
<br />
<p>
    <a asp-controller="Makes" asp-action="Index" class="btn btn-primary">Back to Makes</a>
</p>